#!/bin/bash
#
# Gives the UI a real-looking local address — http://claude.station instead of
# http://localhost:5173 — by pointing a hosts alias at loopback and having pf
# redirect port 80 to the dev server. Nothing is exposed to the network: the
# alias resolves to 127.0.0.1 and the server still binds to 127.0.0.1 only.
#
# Trade-off: while this is installed, http://127.0.0.1:5173 stops answering. pf
# owns that port as the redirect target and reverse-translates the replies of a
# direct connection too, so the alias becomes the only way in.
#
# Idempotent: safe to re-run (a macOS upgrade can reset /etc/pf.conf).
# Undo with scripts/teardown-host.sh.
#
# Usage: sudo bash scripts/setup-host.sh [--host claude.station] [--port 5173]

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MARKER="# claude-station"
ANCHOR_NAME="claude-station"
ANCHOR_FILE="/etc/pf.anchors/claude-station"
PF_CONF="/etc/pf.conf"
PF_BACKUP="/etc/pf.conf.claude-station.bak"
PLIST="/Library/LaunchDaemons/com.claude-station.pf.plist"

HOST="claude.station"
PORT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host) HOST="${2:?--host needs a value}"; shift 2 ;;
    --port) PORT="${2:?--port needs a value}"; shift 2 ;;
    -h|--help) sed -n '2,12p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This script is macOS-only (it uses pf and launchd)." >&2
  exit 1
fi

if [[ "${EUID}" -ne 0 ]]; then
  echo "Needs root — it edits /etc/hosts and /etc/pf.conf." >&2
  echo "Run: sudo bash scripts/setup-host.sh" >&2
  exit 1
fi

# Default to whatever port the dev server is on, so the redirect matches the
# way the app is normally started.
if [[ -z "${PORT}" ]]; then
  PORT="$(sed -n 's/^[[:space:]]*WEB_PORT[[:space:]]*=[[:space:]]*\([0-9]\{1,\}\).*/\1/p' "${REPO_ROOT}/.env" 2>/dev/null | tail -1)"
  PORT="${PORT:-5173}"
fi

echo "→ ${HOST} → 127.0.0.1:${PORT}"

# ---------------------------------------------------------------- 1. /etc/hosts
if grep -qE "^[^#]*[[:space:]]${HOST}([[:space:]]|$)" /etc/hosts; then
  echo "  hosts        already maps ${HOST} — left alone"
else
  printf '\n127.0.0.1\t%s\t%s\n' "${HOST}" "${MARKER}" >> /etc/hosts
  echo "  hosts        added 127.0.0.1 ${HOST}"
fi

# ------------------------------------------------------- 2. the redirect anchor
# rdr on lo0 is what makes port 80 reachable without running the dev server as
# root. Locally-generated traffic to 127.0.0.1:80 gets rewritten to the app port.
#
# Deliberately no `pass` keyword: that turns the rule into a stateful filter
# rule, and the state it keeps on lo0 makes direct connections to the target
# port (127.0.0.1:5173) fail intermittently. Translation only, filtering left to
# the default-pass ruleset, keeps both addresses working.
cat > "${ANCHOR_FILE}" <<EOF
${MARKER} — port 80 on loopback goes to the app. Regenerated by scripts/setup-host.sh.
rdr on lo0 inet proto tcp from any to 127.0.0.1 port 80 -> 127.0.0.1 port ${PORT}
EOF
echo "  pf anchor    wrote ${ANCHOR_FILE}"

# --------------------------------------------------------------- 3. /etc/pf.conf
# An anchor pf.conf never references is never evaluated, so these two lines are
# not optional. Order matters: rdr-anchor must sit with the other rdr rules,
# before any filter rules, or pfctl rejects the whole file.
if grep -q "\"${ANCHOR_NAME}\"" "${PF_CONF}"; then
  echo "  pf.conf      already references the anchor — left alone"
else
  [[ -f "${PF_BACKUP}" ]] || cp "${PF_CONF}" "${PF_BACKUP}"
  python3 - "${PF_CONF}" "${ANCHOR_NAME}" "${ANCHOR_FILE}" "${MARKER}" <<'PY'
import sys

path, anchor, anchor_file, marker = sys.argv[1:5]
lines = open(path).read().splitlines()

rdr = f'rdr-anchor "{anchor}" {marker}'
load = f'load anchor "{anchor}" from "{anchor_file}" {marker}'

# Right after the last rdr-anchor keeps us inside the translation section, which
# pf requires to come before filter rules.
last_rdr = max((i for i, l in enumerate(lines) if l.strip().startswith("rdr-anchor")), default=None)
if last_rdr is None:
    # No rdr section at all: it has to precede the first filter/anchor rule.
    last_rdr = next((i for i, l in enumerate(lines)
                     if l.strip().startswith(("anchor", "pass", "block", "scrub-anchor"))), len(lines)) - 1
lines.insert(last_rdr + 1, rdr)
lines.append(load)

open(path, "w").write("\n".join(lines) + "\n")
PY
  echo "  pf.conf      added the anchor (backup: ${PF_BACKUP})"
fi

# ------------------------------------------------------------- 4. survive reboot
cat > "${PLIST}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.claude-station.pf</string>
  <key>ProgramArguments</key>
  <array>
    <string>/sbin/pfctl</string>
    <string>-E</string>
    <string>-f</string>
    <string>${PF_CONF}</string>
  </array>
  <key>RunAtLoad</key><true/>
</dict>
</plist>
EOF
chmod 644 "${PLIST}"
launchctl bootout system "${PLIST}" 2>/dev/null || true
launchctl bootstrap system "${PLIST}"
echo "  launchd      installed ${PLIST}"

# Load now so no reboot is needed. -E enables pf and bumps its reference count;
# a benign "pf enabled" / "Token : ..." on stderr is normal here.
pfctl -E -f "${PF_CONF}" 2>&1 | sed 's/^/               /'

echo
echo "Done. Add this to ${REPO_ROOT}/.env:"
echo
echo "    STATION_HOST=${HOST}"
echo
echo "Then \`npm run dev\` and open http://${HOST} — the token link is in the banner."
echo "Undo everything with: sudo npm run teardown:host"
